-- Minimal Snowflake foundation for the RAW ingestion phase.
USE ROLE ACCOUNTADMIN;
ALTER SESSION SET QUERY_TAG = 'PHARMARETAIL_RAW_FOUNDATION';

CREATE DATABASE IF NOT EXISTS PHARMARETAIL
DATA_RETENTION_TIME_IN_DAYS = 1
COMMENT = 'PharmaRetail governed analytics database';

ALTER DATABASE PHARMARETAIL SET
DATA_RETENTION_TIME_IN_DAYS = 1
COMMENT = 'PharmaRetail governed analytics database';

DROP SCHEMA IF EXISTS PHARMARETAIL.PUBLIC;

CREATE SCHEMA IF NOT EXISTS PHARMARETAIL.RAW
WITH MANAGED ACCESS
DATA_RETENTION_TIME_IN_DAYS = 1
COMMENT = 'Source-aligned, lossless landing data';

CREATE SCHEMA IF NOT EXISTS PHARMARETAIL.STAGING
WITH MANAGED ACCESS
DATA_RETENTION_TIME_IN_DAYS = 1
COMMENT = 'Typed source cleaning; intentionally empty in this phase';

CREATE SCHEMA IF NOT EXISTS PHARMARETAIL.MARTS
WITH MANAGED ACCESS
DATA_RETENTION_TIME_IN_DAYS = 1
COMMENT = 'Business marts; intentionally empty in this phase';

CREATE SCHEMA IF NOT EXISTS PHARMARETAIL.GOVERNANCE
WITH MANAGED ACCESS
DATA_RETENTION_TIME_IN_DAYS = 1
COMMENT = 'Data governance metadata and policies';

CREATE SCHEMA IF NOT EXISTS PHARMARETAIL.AI_LOGS
WITH MANAGED ACCESS
DATA_RETENTION_TIME_IN_DAYS = 1
COMMENT = 'Reserved AI audit schema; intentionally empty in this phase';
