-- Typed RAW tables matching the existing processed files.
USE ROLE ACCOUNTADMIN;
USE DATABASE PHARMARETAIL;
USE SCHEMA RAW;
ALTER SESSION SET QUERY_TAG = 'PHARMARETAIL_RAW_TABLE_DDL';

CREATE TABLE IF NOT EXISTS PHARMARETAIL.RAW.STORE_SEED (
    STORE_ID STRING NOT NULL,
    STORE_NAME STRING NOT NULL,
    STATE STRING NOT NULL,
    POSTCODE STRING,
    LATITUDE FLOAT NOT NULL,
    LONGITUDE FLOAT NOT NULL,
    REGION STRING NOT NULL,
    POSTCODE_AVAILABLE_FLAG BOOLEAN NOT NULL,
    _SOURCE_FILE STRING NOT NULL,
    _LOADED_AT TIMESTAMP_NTZ NOT NULL
)
COMMENT = 'Lossless landing for data/processed/dim_store_seed.csv with postcode availability';

CREATE TABLE IF NOT EXISTS PHARMARETAIL.RAW.PRODUCT_SEED (
    PRODUCT_ID STRING NOT NULL,
    PRODUCT_NAME STRING NOT NULL,
    BRAND STRING NOT NULL,
    CATEGORY STRING NOT NULL,
    PACK_SIZE STRING NOT NULL,
    COLD_CHAIN_FLAG NUMBER(1, 0) NOT NULL,
    REGULATED_PRODUCT_FLAG NUMBER(1, 0) NOT NULL,
    _SOURCE_FILE STRING NOT NULL,
    _LOADED_AT TIMESTAMP_NTZ NOT NULL
)
COMMENT = 'Lossless landing for data/processed/dim_product_seed.csv';

CREATE TABLE IF NOT EXISTS PHARMARETAIL.RAW.UCI_SALES (
    INVOICE STRING NOT NULL,
    STOCK_CODE STRING NOT NULL,
    DESCRIPTION STRING,
    QUANTITY NUMBER(38, 0) NOT NULL,
    INVOICE_DATE TIMESTAMP_NTZ NOT NULL,
    PRICE FLOAT NOT NULL,
    CUSTOMER_ID STRING,
    COUNTRY STRING NOT NULL,
    IS_CUSTOMER_IDENTIFIED BOOLEAN NOT NULL,
    _SOURCE_FILE STRING NOT NULL,
    _LOADED_AT TIMESTAMP_NTZ NOT NULL
)
COMMENT = 'Lossless landing for data/processed/uci_sales_clean.parquet';

CREATE TABLE IF NOT EXISTS PHARMARETAIL.RAW.UCI_RETURNS (
    INVOICE STRING NOT NULL,
    STOCK_CODE STRING NOT NULL,
    DESCRIPTION STRING,
    QUANTITY NUMBER(38, 0) NOT NULL,
    INVOICE_DATE TIMESTAMP_NTZ NOT NULL,
    PRICE FLOAT NOT NULL,
    CUSTOMER_ID STRING,
    COUNTRY STRING NOT NULL,
    IS_CUSTOMER_IDENTIFIED BOOLEAN NOT NULL,
    _SOURCE_FILE STRING NOT NULL,
    _LOADED_AT TIMESTAMP_NTZ NOT NULL
)
COMMENT = 'Lossless landing for data/processed/uci_returns_clean.parquet';

CREATE TABLE IF NOT EXISTS PHARMARETAIL.RAW.UCI_INVALID_PRICE (
    INVOICE STRING NOT NULL,
    STOCK_CODE STRING NOT NULL,
    DESCRIPTION STRING,
    QUANTITY NUMBER(38, 0) NOT NULL,
    INVOICE_DATE TIMESTAMP_NTZ NOT NULL,
    PRICE FLOAT NOT NULL,
    CUSTOMER_ID STRING,
    COUNTRY STRING NOT NULL,
    IS_CUSTOMER_IDENTIFIED BOOLEAN NOT NULL,
    QUARANTINE_REASON STRING NOT NULL,
    _SOURCE_FILE STRING NOT NULL,
    _LOADED_AT TIMESTAMP_NTZ NOT NULL
)
COMMENT = 'Lossless landing for data/quarantine/uci_invalid_price.parquet';
