-- Cost-controlled project compute. Run with ACCOUNTADMIN during bootstrap.
USE ROLE ACCOUNTADMIN;
ALTER SESSION SET QUERY_TAG = 'PHARMARETAIL_FOUNDATION_WAREHOUSE';

CREATE WAREHOUSE IF NOT EXISTS WH_PHARMARETAIL
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE
COMMENT = 'Cost-controlled compute for PharmaRetail AI Control Tower';

-- Reconcile mutable settings on repeat runs without replacing the warehouse.
ALTER WAREHOUSE WH_PHARMARETAIL SET
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
COMMENT = 'Cost-controlled compute for PharmaRetail AI Control Tower';

GRANT OWNERSHIP ON WAREHOUSE WH_PHARMARETAIL
TO ROLE PHARMARETAIL_ADMIN COPY CURRENT GRANTS;
