-- Isolated project database and managed-access schemas. ABS_DATA is out of scope.
USE ROLE ACCOUNTADMIN;
ALTER SESSION SET QUERY_TAG = 'PHARMARETAIL_FOUNDATION_DATABASE';

CREATE DATABASE IF NOT EXISTS PHARMARETAIL_AI_CONTROL_TOWER
DATA_RETENTION_TIME_IN_DAYS = 1
COMMENT = 'Governed data foundation for PharmaRetail AI Control Tower';

ALTER DATABASE PHARMARETAIL_AI_CONTROL_TOWER SET
DATA_RETENTION_TIME_IN_DAYS = 1
COMMENT = 'Governed data foundation for PharmaRetail AI Control Tower';

-- Remove the generic default schema so project access is explicit.
DROP SCHEMA IF EXISTS PHARMARETAIL_AI_CONTROL_TOWER.PUBLIC;

CREATE SCHEMA IF NOT EXISTS PHARMARETAIL_AI_CONTROL_TOWER.RAW
WITH MANAGED ACCESS
DATA_RETENTION_TIME_IN_DAYS = 1
COMMENT = 'Immutable source-aligned landing objects';

CREATE SCHEMA IF NOT EXISTS PHARMARETAIL_AI_CONTROL_TOWER.STAGING
WITH MANAGED ACCESS
DATA_RETENTION_TIME_IN_DAYS = 1
COMMENT = 'Typed and source-cleaned staging models';

CREATE SCHEMA IF NOT EXISTS PHARMARETAIL_AI_CONTROL_TOWER.INTERMEDIATE
WITH MANAGED ACCESS
DATA_RETENTION_TIME_IN_DAYS = 1
COMMENT = 'Reusable transformation logic not exposed to consumers';

CREATE SCHEMA IF NOT EXISTS PHARMARETAIL_AI_CONTROL_TOWER.MARTS
WITH MANAGED ACCESS
DATA_RETENTION_TIME_IN_DAYS = 1
COMMENT = 'Governed dimensional and semantic consumption layer';

CREATE SCHEMA IF NOT EXISTS PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE
WITH MANAGED ACCESS
DATA_RETENTION_TIME_IN_DAYS = 1
COMMENT = 'Policies, access references and governance metadata';

CREATE SCHEMA IF NOT EXISTS PHARMARETAIL_AI_CONTROL_TOWER.AI_LOGS
WITH MANAGED ACCESS
DATA_RETENTION_TIME_IN_DAYS = 1
COMMENT = 'Controlled AI application telemetry and audit records';

GRANT OWNERSHIP ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.RAW
TO ROLE PHARMARETAIL_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.STAGING
TO ROLE PHARMARETAIL_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.INTERMEDIATE
TO ROLE PHARMARETAIL_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
TO ROLE PHARMARETAIL_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE
TO ROLE PHARMARETAIL_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.AI_LOGS
TO ROLE PHARMARETAIL_ADMIN COPY CURRENT GRANTS;

GRANT OWNERSHIP ON DATABASE PHARMARETAIL_AI_CONTROL_TOWER
TO ROLE PHARMARETAIL_ADMIN COPY CURRENT GRANTS;
