-- Run with SnowSQL or the Python connector from the repository root so PUT can
-- resolve the local data paths. Existing processed files are read, never changed.
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_PHARMARETAIL;
USE DATABASE PHARMARETAIL;
USE SCHEMA RAW;
ALTER SESSION SET QUERY_TAG = 'PHARMARETAIL_RAW_DATA_LOAD';

CREATE FILE FORMAT IF NOT EXISTS PHARMARETAIL.RAW.SEED_CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
NULL_IF = ('');

CREATE FILE FORMAT IF NOT EXISTS PHARMARETAIL.RAW.CLEAN_PARQUET_FORMAT
TYPE = PARQUET;

CREATE STAGE IF NOT EXISTS PHARMARETAIL.RAW.RAW_LOAD_STAGE
    COMMENT = 'Transient landing stage for the five governed local source files';

PUT 'file://data/processed/dim_store_seed.csv'
@PHARMARETAIL.RAW.RAW_LOAD_STAGE
AUTO_COMPRESS = FALSE
OVERWRITE = TRUE;

PUT 'file://data/processed/dim_product_seed.csv'
@PHARMARETAIL.RAW.RAW_LOAD_STAGE
AUTO_COMPRESS = FALSE
OVERWRITE = TRUE;

PUT 'file://data/processed/uci_sales_clean.parquet'
@PHARMARETAIL.RAW.RAW_LOAD_STAGE
AUTO_COMPRESS = FALSE
OVERWRITE = TRUE;

PUT 'file://data/processed/uci_returns_clean.parquet'
@PHARMARETAIL.RAW.RAW_LOAD_STAGE
AUTO_COMPRESS = FALSE
OVERWRITE = TRUE;

PUT 'file://data/quarantine/uci_invalid_price.parquet'
@PHARMARETAIL.RAW.RAW_LOAD_STAGE
AUTO_COMPRESS = FALSE
OVERWRITE = TRUE;

TRUNCATE TABLE PHARMARETAIL.RAW.STORE_SEED;

COPY INTO PHARMARETAIL.RAW.STORE_SEED (
    STORE_ID,
    STORE_NAME,
    STATE,
    POSTCODE,
    LATITUDE,
    LONGITUDE,
    REGION,
    POSTCODE_AVAILABLE_FLAG,
    _SOURCE_FILE,
    _LOADED_AT
)
FROM (
    SELECT  -- noqa: ST06
        $1::STRING AS STORE_ID,
        $2::STRING AS STORE_NAME,
        $3::STRING AS STATE,
        $4::STRING AS POSTCODE,
        $5::FLOAT AS LATITUDE,
        $6::FLOAT AS LONGITUDE,
        $7::STRING AS REGION,
        $4 IS NOT NULL AS POSTCODE_AVAILABLE_FLAG,
        'data/processed/dim_store_seed.csv' AS _SOURCE_FILE,
        CURRENT_TIMESTAMP() AS _LOADED_AT
    FROM @PHARMARETAIL.RAW.RAW_LOAD_STAGE/dim_store_seed.csv
)
FILE_FORMAT = (FORMAT_NAME = 'PHARMARETAIL.RAW.SEED_CSV_FORMAT')
FORCE = TRUE
ON_ERROR = 'ABORT_STATEMENT';

TRUNCATE TABLE PHARMARETAIL.RAW.PRODUCT_SEED;

COPY INTO PHARMARETAIL.RAW.PRODUCT_SEED (
    PRODUCT_ID,
    PRODUCT_NAME,
    BRAND,
    CATEGORY,
    PACK_SIZE,
    COLD_CHAIN_FLAG,
    REGULATED_PRODUCT_FLAG,
    _SOURCE_FILE,
    _LOADED_AT
)
FROM (
    SELECT
        $1::STRING AS PRODUCT_ID,
        $2::STRING AS PRODUCT_NAME,
        $3::STRING AS BRAND,
        $4::STRING AS CATEGORY,
        $5::STRING AS PACK_SIZE,
        $6::NUMBER(1, 0) AS COLD_CHAIN_FLAG,
        $7::NUMBER(1, 0) AS REGULATED_PRODUCT_FLAG,
        'data/processed/dim_product_seed.csv' AS _SOURCE_FILE,
        CURRENT_TIMESTAMP() AS _LOADED_AT
    FROM @PHARMARETAIL.RAW.RAW_LOAD_STAGE/dim_product_seed.csv
)
FILE_FORMAT = (FORMAT_NAME = 'PHARMARETAIL.RAW.SEED_CSV_FORMAT')
FORCE = TRUE
ON_ERROR = 'ABORT_STATEMENT';

TRUNCATE TABLE PHARMARETAIL.RAW.UCI_SALES;

COPY INTO PHARMARETAIL.RAW.UCI_SALES (
    INVOICE,
    STOCK_CODE,
    DESCRIPTION,
    QUANTITY,
    INVOICE_DATE,
    PRICE,
    CUSTOMER_ID,
    COUNTRY,
    IS_CUSTOMER_IDENTIFIED,
    _SOURCE_FILE,
    _LOADED_AT
)
FROM (
    SELECT  -- noqa: ST06
        $1:invoice::STRING AS INVOICE,
        $1:stock_code::STRING AS STOCK_CODE,
        $1:description::STRING AS DESCRIPTION,
        $1:quantity::NUMBER(38, 0) AS QUANTITY,
        TO_TIMESTAMP_NTZ($1:invoice_date::NUMBER, 9) AS INVOICE_DATE,
        $1:price::FLOAT AS PRICE,
        $1:customer_id::STRING AS CUSTOMER_ID,
        $1:country::STRING AS COUNTRY,
        $1:is_customer_identified::BOOLEAN AS IS_CUSTOMER_IDENTIFIED,
        'data/processed/uci_sales_clean.parquet' AS _SOURCE_FILE,
        CURRENT_TIMESTAMP() AS _LOADED_AT
    FROM @PHARMARETAIL.RAW.RAW_LOAD_STAGE/uci_sales_clean.parquet
)
FILE_FORMAT = (FORMAT_NAME = 'PHARMARETAIL.RAW.CLEAN_PARQUET_FORMAT')
FORCE = TRUE
ON_ERROR = 'ABORT_STATEMENT';

TRUNCATE TABLE PHARMARETAIL.RAW.UCI_RETURNS;

COPY INTO PHARMARETAIL.RAW.UCI_RETURNS (
    INVOICE,
    STOCK_CODE,
    DESCRIPTION,
    QUANTITY,
    INVOICE_DATE,
    PRICE,
    CUSTOMER_ID,
    COUNTRY,
    IS_CUSTOMER_IDENTIFIED,
    _SOURCE_FILE,
    _LOADED_AT
)
FROM (
    SELECT  -- noqa: ST06
        $1:invoice::STRING AS INVOICE,
        $1:stock_code::STRING AS STOCK_CODE,
        $1:description::STRING AS DESCRIPTION,
        $1:quantity::NUMBER(38, 0) AS QUANTITY,
        TO_TIMESTAMP_NTZ($1:invoice_date::NUMBER, 9) AS INVOICE_DATE,
        $1:price::FLOAT AS PRICE,
        $1:customer_id::STRING AS CUSTOMER_ID,
        $1:country::STRING AS COUNTRY,
        $1:is_customer_identified::BOOLEAN AS IS_CUSTOMER_IDENTIFIED,
        'data/processed/uci_returns_clean.parquet' AS _SOURCE_FILE,
        CURRENT_TIMESTAMP() AS _LOADED_AT
    FROM @PHARMARETAIL.RAW.RAW_LOAD_STAGE/uci_returns_clean.parquet
)
FILE_FORMAT = (FORMAT_NAME = 'PHARMARETAIL.RAW.CLEAN_PARQUET_FORMAT')
FORCE = TRUE
ON_ERROR = 'ABORT_STATEMENT';

TRUNCATE TABLE PHARMARETAIL.RAW.UCI_INVALID_PRICE;

COPY INTO PHARMARETAIL.RAW.UCI_INVALID_PRICE (
    INVOICE,
    STOCK_CODE,
    DESCRIPTION,
    QUANTITY,
    INVOICE_DATE,
    PRICE,
    CUSTOMER_ID,
    COUNTRY,
    IS_CUSTOMER_IDENTIFIED,
    QUARANTINE_REASON,
    _SOURCE_FILE,
    _LOADED_AT
)
FROM (
    SELECT  -- noqa: ST06
        $1:invoice::STRING AS INVOICE,
        $1:stock_code::STRING AS STOCK_CODE,
        $1:description::STRING AS DESCRIPTION,
        $1:quantity::NUMBER(38, 0) AS QUANTITY,
        TO_TIMESTAMP_NTZ($1:invoice_date::NUMBER, 9) AS INVOICE_DATE,
        $1:price::FLOAT AS PRICE,
        $1:customer_id::STRING AS CUSTOMER_ID,
        $1:country::STRING AS COUNTRY,
        $1:is_customer_identified::BOOLEAN AS IS_CUSTOMER_IDENTIFIED,
        $1:quarantine_reason::STRING AS QUARANTINE_REASON,
        'data/quarantine/uci_invalid_price.parquet' AS _SOURCE_FILE,
        CURRENT_TIMESTAMP() AS _LOADED_AT
    FROM @PHARMARETAIL.RAW.RAW_LOAD_STAGE/uci_invalid_price.parquet
)
FILE_FORMAT = (FORMAT_NAME = 'PHARMARETAIL.RAW.CLEAN_PARQUET_FORMAT')
FORCE = TRUE
ON_ERROR = 'ABORT_STATEMENT';

REMOVE @PHARMARETAIL.RAW.RAW_LOAD_STAGE/dim_store_seed.csv;
REMOVE @PHARMARETAIL.RAW.RAW_LOAD_STAGE/dim_product_seed.csv;
REMOVE @PHARMARETAIL.RAW.RAW_LOAD_STAGE/uci_sales_clean.parquet;
REMOVE @PHARMARETAIL.RAW.RAW_LOAD_STAGE/uci_returns_clean.parquet;
REMOVE @PHARMARETAIL.RAW.RAW_LOAD_STAGE/uci_invalid_price.parquet;
