-- Least-privilege current and future grants. PHARMARETAIL_ADMIN owns all targets.
USE ROLE PHARMARETAIL_ADMIN;
ALTER SESSION SET QUERY_TAG = 'PHARMARETAIL_FOUNDATION_GRANTS';

-- Dedicated warehouse access. Auto-resume allows query roles to use compute
-- without granting broad warehouse administration privileges.
GRANT USAGE, OPERATE, MONITOR ON WAREHOUSE WH_PHARMARETAIL
TO ROLE PHARMARETAIL_ENGINEER;
GRANT USAGE, MONITOR ON WAREHOUSE WH_PHARMARETAIL
TO ROLE PHARMARETAIL_DBT;
GRANT USAGE ON WAREHOUSE WH_PHARMARETAIL
TO ROLE PHARMARETAIL_AI_APP;
GRANT USAGE ON WAREHOUSE WH_PHARMARETAIL
TO ROLE PHARMARETAIL_READONLY;
GRANT USAGE ON WAREHOUSE WH_PHARMARETAIL
TO ROLE PHARMARETAIL_STORE_MANAGER;
GRANT USAGE ON WAREHOUSE WH_PHARMARETAIL
TO ROLE PHARMARETAIL_AREA_MANAGER;
GRANT USAGE ON WAREHOUSE WH_PHARMARETAIL
TO ROLE PHARMARETAIL_SUPPLY_CHAIN_ANALYST;

GRANT USAGE ON DATABASE PHARMARETAIL_AI_CONTROL_TOWER
TO ROLE PHARMARETAIL_ENGINEER;
GRANT USAGE ON DATABASE PHARMARETAIL_AI_CONTROL_TOWER
TO ROLE PHARMARETAIL_DBT;
GRANT USAGE ON DATABASE PHARMARETAIL_AI_CONTROL_TOWER
TO ROLE PHARMARETAIL_AI_APP;
GRANT USAGE ON DATABASE PHARMARETAIL_AI_CONTROL_TOWER
TO ROLE PHARMARETAIL_READONLY;
GRANT USAGE ON DATABASE PHARMARETAIL_AI_CONTROL_TOWER
TO ROLE PHARMARETAIL_STORE_MANAGER;
GRANT USAGE ON DATABASE PHARMARETAIL_AI_CONTROL_TOWER
TO ROLE PHARMARETAIL_AREA_MANAGER;
GRANT USAGE ON DATABASE PHARMARETAIL_AI_CONTROL_TOWER
TO ROLE PHARMARETAIL_SUPPLY_CHAIN_ANALYST;

-- ENGINEER develops from RAW through MARTS, but has no GOVERNANCE or AI_LOGS access.
GRANT USAGE ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.RAW
TO ROLE PHARMARETAIL_ENGINEER;
GRANT USAGE ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.STAGING
TO ROLE PHARMARETAIL_ENGINEER;
GRANT USAGE ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.INTERMEDIATE
TO ROLE PHARMARETAIL_ENGINEER;
GRANT USAGE ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
TO ROLE PHARMARETAIL_ENGINEER;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE SEQUENCE
ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.RAW
TO ROLE PHARMARETAIL_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE
ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.STAGING
TO ROLE PHARMARETAIL_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE
ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.INTERMEDIATE
TO ROLE PHARMARETAIL_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE
ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
TO ROLE PHARMARETAIL_ENGINEER;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON ALL TABLES IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.RAW
TO ROLE PHARMARETAIL_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON ALL TABLES IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.STAGING
TO ROLE PHARMARETAIL_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON ALL TABLES IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.INTERMEDIATE
TO ROLE PHARMARETAIL_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON ALL TABLES IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
TO ROLE PHARMARETAIL_ENGINEER;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.RAW
TO ROLE PHARMARETAIL_ENGINEER;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.STAGING
TO ROLE PHARMARETAIL_ENGINEER;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.INTERMEDIATE
TO ROLE PHARMARETAIL_ENGINEER;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
TO ROLE PHARMARETAIL_ENGINEER;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON FUTURE TABLES IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.RAW
TO ROLE PHARMARETAIL_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON FUTURE TABLES IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.STAGING
TO ROLE PHARMARETAIL_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON FUTURE TABLES IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.INTERMEDIATE
TO ROLE PHARMARETAIL_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON FUTURE TABLES IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
TO ROLE PHARMARETAIL_ENGINEER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.RAW
TO ROLE PHARMARETAIL_ENGINEER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.STAGING
TO ROLE PHARMARETAIL_ENGINEER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.INTERMEDIATE
TO ROLE PHARMARETAIL_ENGINEER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
TO ROLE PHARMARETAIL_ENGINEER;

-- DBT reads RAW and creates or maintains models only in modelling schemas.
GRANT USAGE ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.RAW
TO ROLE PHARMARETAIL_DBT;
GRANT USAGE ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.STAGING
TO ROLE PHARMARETAIL_DBT;
GRANT USAGE ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.INTERMEDIATE
TO ROLE PHARMARETAIL_DBT;
GRANT USAGE ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
TO ROLE PHARMARETAIL_DBT;
-- Required only to resolve the two specific policy objects granted with APPLY
-- in 10_phase4_governance.sql. DBT receives no GOVERNANCE table/view access.
GRANT USAGE ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE
TO ROLE PHARMARETAIL_DBT;

GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE
ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.STAGING
TO ROLE PHARMARETAIL_DBT;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE
ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.INTERMEDIATE
TO ROLE PHARMARETAIL_DBT;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE
ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
TO ROLE PHARMARETAIL_DBT;

GRANT SELECT ON ALL TABLES IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.RAW
TO ROLE PHARMARETAIL_DBT;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.RAW
TO ROLE PHARMARETAIL_DBT;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.RAW
TO ROLE PHARMARETAIL_DBT;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.RAW
TO ROLE PHARMARETAIL_DBT;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON ALL TABLES IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.STAGING
TO ROLE PHARMARETAIL_DBT;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON ALL TABLES IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.INTERMEDIATE
TO ROLE PHARMARETAIL_DBT;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON ALL TABLES IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
TO ROLE PHARMARETAIL_DBT;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.STAGING
TO ROLE PHARMARETAIL_DBT;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.INTERMEDIATE
TO ROLE PHARMARETAIL_DBT;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
TO ROLE PHARMARETAIL_DBT;

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON FUTURE TABLES IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.STAGING
TO ROLE PHARMARETAIL_DBT;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON FUTURE TABLES IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.INTERMEDIATE
TO ROLE PHARMARETAIL_DBT;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
ON FUTURE TABLES IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
TO ROLE PHARMARETAIL_DBT;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.STAGING
TO ROLE PHARMARETAIL_DBT;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.INTERMEDIATE
TO ROLE PHARMARETAIL_DBT;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
TO ROLE PHARMARETAIL_DBT;

-- AI_APP reads curated marts and governance references, and can only append to
-- administrator-created AI_LOGS tables. It cannot create log tables or read RAW.
GRANT USAGE ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
TO ROLE PHARMARETAIL_AI_APP;
GRANT USAGE ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE
TO ROLE PHARMARETAIL_AI_APP;
GRANT USAGE ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.AI_LOGS
TO ROLE PHARMARETAIL_AI_APP;
GRANT SELECT ON ALL TABLES IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE
TO ROLE PHARMARETAIL_AI_APP;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE
TO ROLE PHARMARETAIL_AI_APP;
GRANT INSERT ON ALL TABLES IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.AI_LOGS
TO ROLE PHARMARETAIL_AI_APP;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE
TO ROLE PHARMARETAIL_AI_APP;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE
TO ROLE PHARMARETAIL_AI_APP;
GRANT INSERT ON FUTURE TABLES IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.AI_LOGS
TO ROLE PHARMARETAIL_AI_APP;

-- Persona roles receive schema usage here, but no broad ALL/FUTURE object
-- grants. The post-dbt phase4_model_grants.sql admin step explicitly grants
-- approved models only, after dbt has created them and attached row policies.
GRANT USAGE ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
TO ROLE PHARMARETAIL_STORE_MANAGER;
GRANT USAGE ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
TO ROLE PHARMARETAIL_AREA_MANAGER;
GRANT USAGE ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
TO ROLE PHARMARETAIL_SUPPLY_CHAIN_ANALYST;
GRANT USAGE ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE
TO ROLE PHARMARETAIL_SUPPLY_CHAIN_ANALYST;

-- READONLY has no object access outside MARTS.
GRANT USAGE ON SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
TO ROLE PHARMARETAIL_READONLY;
GRANT SELECT ON ALL TABLES IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
TO ROLE PHARMARETAIL_READONLY;
GRANT SELECT ON ALL VIEWS IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
TO ROLE PHARMARETAIL_READONLY;
GRANT SELECT ON FUTURE TABLES IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
TO ROLE PHARMARETAIL_READONLY;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
TO ROLE PHARMARETAIL_READONLY;
