-- Account-level cost guardrail for the dedicated project warehouse.
USE ROLE ACCOUNTADMIN;
ALTER SESSION SET QUERY_TAG = 'PHARMARETAIL_FOUNDATION_COST_GUARDRAIL';

CREATE RESOURCE MONITOR IF NOT EXISTS RM_PHARMARETAIL_MONTHLY
WITH
    CREDIT_QUOTA = 20
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
    TRIGGERS
        ON 50 PERCENT DO NOTIFY
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO SUSPEND
        ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER RESOURCE MONITOR RM_PHARMARETAIL_MONTHLY SET
    CREDIT_QUOTA = 20
    TRIGGERS
        ON 50 PERCENT DO NOTIFY
        ON 75 PERCENT DO NOTIFY
        ON 90 PERCENT DO SUSPEND
        ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE WH_PHARMARETAIL SET
    RESOURCE_MONITOR = RM_PHARMARETAIL_MONTHLY;

GRANT MONITOR, MODIFY ON RESOURCE MONITOR RM_PHARMARETAIL_MONTHLY
TO ROLE PHARMARETAIL_ADMIN;
