-- Read-only foundation inventory. Automated allow/deny tests live in
-- scripts/validate_snowflake_foundation.py and clean up their smoke objects.
USE ROLE PHARMARETAIL_ADMIN;
ALTER SESSION SET QUERY_TAG = 'PHARMARETAIL_FOUNDATION_SQL_VALIDATION';

SELECT
    CURRENT_ACCOUNT() AS ACCOUNT_NAME,
    CURRENT_USER() AS USER_NAME,
    CURRENT_ROLE() AS ROLE_NAME,
    CURRENT_SESSION() AS SESSION_ID;

SHOW WAREHOUSES LIKE 'WH_PHARMARETAIL';
SHOW DATABASES LIKE 'PHARMARETAIL_AI_CONTROL_TOWER';
SHOW SCHEMAS IN DATABASE PHARMARETAIL_AI_CONTROL_TOWER;
SHOW RESOURCE MONITORS LIKE 'RM_PHARMARETAIL_MONTHLY';

SHOW GRANTS TO ROLE PHARMARETAIL_ADMIN;
SHOW GRANTS TO ROLE PHARMARETAIL_ENGINEER;
SHOW GRANTS TO ROLE PHARMARETAIL_DBT;
SHOW GRANTS TO ROLE PHARMARETAIL_AI_APP;
SHOW GRANTS TO ROLE PHARMARETAIL_READONLY;

SHOW FUTURE GRANTS TO ROLE PHARMARETAIL_ENGINEER;
SHOW FUTURE GRANTS TO ROLE PHARMARETAIL_DBT;
SHOW FUTURE GRANTS TO ROLE PHARMARETAIL_AI_APP;
SHOW FUTURE GRANTS TO ROLE PHARMARETAIL_READONLY;
