-- Bootstrap governance objects and policies. Role creation in 01_roles.sql and
-- these policy APPLY grants require the human ACCOUNTADMIN bootstrap path.
-- noqa: disable=CP02,LT02,LT09,PRS
USE ROLE ACCOUNTADMIN;
DESCRIBE USER SVC_PHARMARETAIL_DBT;
SET PHASE3_DBT_USER_QUERY_ID = (SELECT LAST_QUERY_ID());

USE ROLE PHARMARETAIL_ADMIN;
ALTER SESSION SET QUERY_TAG = 'PHARMARETAIL_PHASE4_GOVERNANCE_BOOTSTRAP';

CREATE TABLE IF NOT EXISTS PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.SECURITY_CLOSURE_EVIDENCE (
    USER_NAME VARCHAR NOT NULL,
    RSA_PUBLIC_KEY_FP VARCHAR,
    RSA_PUBLIC_KEY_2_FP VARCHAR,
    VERIFIED_AT TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT PK_SECURITY_CLOSURE_EVIDENCE PRIMARY KEY (USER_NAME)
);

MERGE INTO PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.SECURITY_CLOSURE_EVIDENCE AS target
USING (
    SELECT
        'SVC_PHARMARETAIL_DBT' AS USER_NAME,
        MAX(IFF("property" = 'RSA_PUBLIC_KEY_FP', NULLIF("value", ''), NULL))
            AS RSA_PUBLIC_KEY_FP,
        MAX(IFF("property" = 'RSA_PUBLIC_KEY_2_FP', NULLIF("value", ''), NULL))
            AS RSA_PUBLIC_KEY_2_FP,
        CURRENT_TIMESTAMP() AS VERIFIED_AT
    FROM TABLE(RESULT_SCAN($PHASE3_DBT_USER_QUERY_ID))
) AS source
ON target.USER_NAME = source.USER_NAME
WHEN MATCHED THEN UPDATE SET
    RSA_PUBLIC_KEY_FP = source.RSA_PUBLIC_KEY_FP,
    RSA_PUBLIC_KEY_2_FP = source.RSA_PUBLIC_KEY_2_FP,
    VERIFIED_AT = source.VERIFIED_AT
WHEN NOT MATCHED THEN INSERT (
    USER_NAME, RSA_PUBLIC_KEY_FP, RSA_PUBLIC_KEY_2_FP, VERIFIED_AT
)
VALUES (
    source.USER_NAME, source.RSA_PUBLIC_KEY_FP, source.RSA_PUBLIC_KEY_2_FP, source.VERIFIED_AT
);

CREATE TABLE IF NOT EXISTS PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.USER_STORE_SCOPE (
    USER_NAME VARCHAR NOT NULL,
    STORE_ID VARCHAR NOT NULL,
    ASSIGNMENT_SOURCE VARCHAR NOT NULL,
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_USER_STORE_SCOPE PRIMARY KEY (USER_NAME, STORE_ID)
);

CREATE TABLE IF NOT EXISTS PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.USER_REGION_SCOPE (
    USER_NAME VARCHAR NOT NULL,
    REGION VARCHAR NOT NULL,
    ASSIGNMENT_SOURCE VARCHAR NOT NULL,
    UPDATED_AT TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_USER_REGION_SCOPE PRIMARY KEY (USER_NAME, REGION)
);

MERGE INTO PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.USER_STORE_SCOPE AS target
USING (
    SELECT COLUMN1 AS USER_NAME, COLUMN2 AS STORE_ID, 'PHASE4_DEMO_ASSIGNMENT' AS ASSIGNMENT_SOURCE
    FROM VALUES
        ('OMRUM', 'CW_OSM_NODE_1247865789'),
        ('SVC_PHARMARETAIL_CICD', 'CW_OSM_NODE_1247865789')
) AS source
ON target.USER_NAME = source.USER_NAME AND target.STORE_ID = source.STORE_ID
WHEN MATCHED THEN UPDATE SET
    ASSIGNMENT_SOURCE = source.ASSIGNMENT_SOURCE,
    UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (USER_NAME, STORE_ID, ASSIGNMENT_SOURCE)
VALUES (source.USER_NAME, source.STORE_ID, source.ASSIGNMENT_SOURCE);

MERGE INTO PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.USER_REGION_SCOPE AS target
USING (
    SELECT COLUMN1 AS USER_NAME, COLUMN2 AS REGION, 'PHASE4_DEMO_ASSIGNMENT' AS ASSIGNMENT_SOURCE
    FROM VALUES
        ('OMRUM', 'VIC & TAS'),
        ('SVC_PHARMARETAIL_CICD', 'VIC & TAS')
) AS source
ON target.USER_NAME = source.USER_NAME AND target.REGION = source.REGION
WHEN MATCHED THEN UPDATE SET
    ASSIGNMENT_SOURCE = source.ASSIGNMENT_SOURCE,
    UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT (USER_NAME, REGION, ASSIGNMENT_SOURCE)
VALUES (source.USER_NAME, source.REGION, source.ASSIGNMENT_SOURCE);

-- The current SQL parser does not yet understand Snowflake policy IF NOT EXISTS
-- grammar; CI still validates the remaining statements and contract tests.
CREATE ROW ACCESS POLICY IF NOT EXISTS
PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.OPERATIONAL_STORE_REGION_POLICY
AS (OPERATIONAL_STORE_ID VARCHAR, OPERATIONAL_REGION VARCHAR) RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() IN (
            'PHARMARETAIL_ADMIN',
            'PHARMARETAIL_DBT',
            'PHARMARETAIL_ENGINEER',
            'PHARMARETAIL_SUPPLY_CHAIN_ANALYST',
            'PHARMARETAIL_AI_APP'
        ) THEN TRUE
        WHEN CURRENT_ROLE() = 'PHARMARETAIL_STORE_MANAGER' THEN EXISTS (
            SELECT 1
            FROM PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.USER_STORE_SCOPE AS scope
            WHERE scope.USER_NAME = CURRENT_USER()
                AND scope.STORE_ID = OPERATIONAL_STORE_ID
        )
        WHEN CURRENT_ROLE() = 'PHARMARETAIL_AREA_MANAGER' THEN EXISTS (
            SELECT 1
            FROM PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.USER_REGION_SCOPE AS scope
            WHERE scope.USER_NAME = CURRENT_USER()
                AND scope.REGION = OPERATIONAL_REGION
        )
        ELSE FALSE
    END;

CREATE MASKING POLICY IF NOT EXISTS
PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.SENSITIVE_TEXT_MASK
AS (VALUE VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN (
            'PHARMARETAIL_ADMIN',
            'PHARMARETAIL_DBT',
            'PHARMARETAIL_ENGINEER'
        ) THEN VALUE
        ELSE '***MASKED***'
    END;

CREATE TABLE IF NOT EXISTS PHARMARETAIL_AI_CONTROL_TOWER.AI_LOGS.OPERATIONAL_ACCESS_AUDIT (
    AUDIT_ID VARCHAR NOT NULL,
    EVENT_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    ACTOR VARCHAR NOT NULL,
    ACTIVE_ROLE VARCHAR NOT NULL,
    QUERY_TAG VARCHAR NOT NULL,
    ACTION_NAME VARCHAR NOT NULL,
    OBJECT_NAME VARCHAR NOT NULL,
    ROW_COUNT NUMBER,
    OUTCOME VARCHAR NOT NULL
);

GRANT APPLY ON ROW ACCESS POLICY
PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.OPERATIONAL_STORE_REGION_POLICY
TO ROLE PHARMARETAIL_DBT;
GRANT APPLY ON MASKING POLICY
PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.SENSITIVE_TEXT_MASK
TO ROLE PHARMARETAIL_DBT;

GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.USER_STORE_SCOPE
TO ROLE PHARMARETAIL_AI_APP;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.USER_REGION_SCOPE
TO ROLE PHARMARETAIL_AI_APP;
GRANT INSERT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.AI_LOGS.OPERATIONAL_ACCESS_AUDIT
TO ROLE PHARMARETAIL_AI_APP;
