-- Governed Phase 5 SOP registry, chunks, embedding metadata and retrieval audit.
-- BAU-safe: all objects remain inside the existing GOVERNANCE schema.
-- noqa: disable=CP02,LT02,LT09,PRS
USE ROLE PHARMARETAIL_ADMIN;
ALTER SESSION SET QUERY_TAG = 'PHARMARETAIL_PHASE5_RAG_DDL';

CREATE TABLE IF NOT EXISTS PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.DOCUMENT_REGISTRY (
    DOC_ID VARCHAR NOT NULL,
    TITLE VARCHAR NOT NULL,
    VERSION VARCHAR NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    COUNTRY VARCHAR NOT NULL,
    BUSINESS_UNIT VARCHAR NOT NULL,
    POLICY_OWNER VARCHAR NOT NULL,
    ACCESS_LEVEL VARCHAR NOT NULL,
    SECTION_ID VARCHAR NOT NULL,
    SOURCE_TYPE VARCHAR NOT NULL,
    SOURCE_FILE VARCHAR NOT NULL,
    CONTENT_HASH VARCHAR NOT NULL,
    DOCUMENT_STATUS VARCHAR NOT NULL,
    INGESTED_AT TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT PK_DOCUMENT_REGISTRY PRIMARY KEY (DOC_ID, VERSION),
    CONSTRAINT CK_DOCUMENT_DATES CHECK (EFFECTIVE_DATE <= EXPIRY_DATE),
    CONSTRAINT CK_DOCUMENT_ACCESS CHECK (ACCESS_LEVEL IN ('PUBLIC', 'INTERNAL', 'RESTRICTED'))
);

CREATE TABLE IF NOT EXISTS PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.DOCUMENT_CHUNKS (
    CHUNK_ID VARCHAR NOT NULL,
    DOC_ID VARCHAR NOT NULL,
    VERSION VARCHAR NOT NULL,
    SECTION_ID VARCHAR NOT NULL,
    SECTION_TITLE VARCHAR NOT NULL,
    CHUNK_INDEX NUMBER NOT NULL,
    CHUNK_TEXT VARCHAR NOT NULL,
    TOKEN_COUNT NUMBER NOT NULL,
    CONTENT_HASH VARCHAR NOT NULL,
    COUNTRY VARCHAR NOT NULL,
    BUSINESS_UNIT VARCHAR NOT NULL,
    ACCESS_LEVEL VARCHAR NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    EMBEDDING VARIANT NOT NULL,
    CREATED_AT TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT PK_DOCUMENT_CHUNKS PRIMARY KEY (CHUNK_ID),
    CONSTRAINT FK_CHUNK_DOCUMENT FOREIGN KEY (DOC_ID, VERSION)
        REFERENCES PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.DOCUMENT_REGISTRY (DOC_ID, VERSION),
    CONSTRAINT CK_CHUNK_DATES CHECK (EFFECTIVE_DATE <= EXPIRY_DATE),
    CONSTRAINT CK_CHUNK_ACCESS CHECK (ACCESS_LEVEL IN ('PUBLIC', 'INTERNAL', 'RESTRICTED'))
);

CREATE TABLE IF NOT EXISTS PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.EMBEDDING_METADATA (
    CHUNK_ID VARCHAR NOT NULL,
    EMBEDDING_MODEL VARCHAR NOT NULL,
    EMBEDDING_VERSION VARCHAR NOT NULL,
    EMBEDDING_DIMENSION NUMBER NOT NULL,
    EMBEDDING_PROVIDER VARCHAR NOT NULL,
    DISTANCE_METRIC VARCHAR NOT NULL,
    CONTENT_HASH VARCHAR NOT NULL,
    GENERATED_AT TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT PK_EMBEDDING_METADATA PRIMARY KEY (CHUNK_ID),
    CONSTRAINT FK_EMBEDDING_CHUNK FOREIGN KEY (CHUNK_ID)
        REFERENCES PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.DOCUMENT_CHUNKS (CHUNK_ID)
);

CREATE TABLE IF NOT EXISTS PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.RETRIEVAL_AUDIT (
    AUDIT_ID VARCHAR NOT NULL,
    EVENT_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    ACTOR VARCHAR NOT NULL,
    ACTOR_ROLE VARCHAR NOT NULL,
    QUERY_HASH VARCHAR NOT NULL,
    COUNTRY_FILTER VARCHAR,
    BUSINESS_UNIT_FILTER VARCHAR,
    AS_OF_DATE DATE NOT NULL,
    RETRIEVED_CHUNK_IDS VARIANT NOT NULL,
    CITATION_COUNT NUMBER NOT NULL,
    UNCERTAINTY VARCHAR NOT NULL,
    REFUSED BOOLEAN NOT NULL,
    REFUSAL_REASON VARCHAR,
    OUTCOME VARCHAR NOT NULL,
    LATENCY_MS NUMBER NOT NULL,
    CONSTRAINT PK_RETRIEVAL_AUDIT PRIMARY KEY (AUDIT_ID)
);

CREATE TABLE IF NOT EXISTS PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.RAG_ROLE_ACCESS_SCOPE (
    ROLE_NAME VARCHAR NOT NULL,
    ACCESS_LEVEL VARCHAR NOT NULL,
    UPDATED_AT TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT PK_RAG_ROLE_ACCESS_SCOPE PRIMARY KEY (ROLE_NAME, ACCESS_LEVEL),
    CONSTRAINT CK_RAG_SCOPE_ACCESS CHECK (ACCESS_LEVEL IN ('PUBLIC', 'INTERNAL', 'RESTRICTED'))
);

MERGE INTO PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.RAG_ROLE_ACCESS_SCOPE AS target
USING (
    SELECT COLUMN1 AS ROLE_NAME, COLUMN2 AS ACCESS_LEVEL, CURRENT_TIMESTAMP() AS UPDATED_AT
    FROM VALUES
        ('PHARMARETAIL_ADMIN', 'PUBLIC'),
        ('PHARMARETAIL_ADMIN', 'INTERNAL'),
        ('PHARMARETAIL_ADMIN', 'RESTRICTED'),
        ('PHARMARETAIL_AI_APP', 'PUBLIC'),
        ('PHARMARETAIL_AI_APP', 'INTERNAL'),
        ('PHARMARETAIL_AI_APP', 'RESTRICTED'),
        ('PHARMARETAIL_SUPPLY_CHAIN_ANALYST', 'PUBLIC'),
        ('PHARMARETAIL_SUPPLY_CHAIN_ANALYST', 'INTERNAL'),
        ('PHARMARETAIL_SUPPLY_CHAIN_ANALYST', 'RESTRICTED'),
        ('PHARMARETAIL_AREA_MANAGER', 'PUBLIC'),
        ('PHARMARETAIL_AREA_MANAGER', 'INTERNAL'),
        ('PHARMARETAIL_STORE_MANAGER', 'PUBLIC'),
        ('PHARMARETAIL_STORE_MANAGER', 'INTERNAL'),
        ('PHARMARETAIL_READONLY', 'PUBLIC')
) AS source
ON target.ROLE_NAME = source.ROLE_NAME AND target.ACCESS_LEVEL = source.ACCESS_LEVEL
WHEN MATCHED THEN UPDATE SET UPDATED_AT = source.UPDATED_AT
WHEN NOT MATCHED THEN INSERT (ROLE_NAME, ACCESS_LEVEL, UPDATED_AT)
VALUES (source.ROLE_NAME, source.ACCESS_LEVEL, source.UPDATED_AT);

GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.DOCUMENT_REGISTRY
TO ROLE PHARMARETAIL_AI_APP;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.DOCUMENT_CHUNKS
TO ROLE PHARMARETAIL_AI_APP;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.EMBEDDING_METADATA
TO ROLE PHARMARETAIL_AI_APP;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.RAG_ROLE_ACCESS_SCOPE
TO ROLE PHARMARETAIL_AI_APP;
GRANT SELECT, INSERT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.RETRIEVAL_AUDIT
TO ROLE PHARMARETAIL_AI_APP;

GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.DOCUMENT_REGISTRY
TO ROLE PHARMARETAIL_SUPPLY_CHAIN_ANALYST;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.DOCUMENT_CHUNKS
TO ROLE PHARMARETAIL_SUPPLY_CHAIN_ANALYST;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.EMBEDDING_METADATA
TO ROLE PHARMARETAIL_SUPPLY_CHAIN_ANALYST;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.GOVERNANCE.RAG_ROLE_ACCESS_SCOPE
TO ROLE PHARMARETAIL_SUPPLY_CHAIN_ANALYST;
