-- Phase 6 governed Stockout Investigation Agent objects.
-- Append-only interaction audit and action-draft tables live in the existing
-- AI_LOGS schema. The agent reads only the Phase 4 marts already granted to
-- PHARMARETAIL_AI_APP in phase4_model_grants.sql; no new read surface is added.
-- noqa: disable=CP02,LT02,LT09,PRS
USE ROLE PHARMARETAIL_ADMIN;
ALTER SESSION SET QUERY_TAG = 'PHARMARETAIL_PHASE6_AGENT_DDL';

CREATE TABLE IF NOT EXISTS PHARMARETAIL_AI_CONTROL_TOWER.AI_LOGS.AGENT_INTERACTION_AUDIT (
    AUDIT_ID VARCHAR NOT NULL,
    EVENT_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    ACTOR VARCHAR NOT NULL,
    ACTOR_ROLE VARCHAR NOT NULL,
    QUERY_HASH VARCHAR NOT NULL,
    STEP_SEQUENCE NUMBER NOT NULL,
    TOOL_NAME VARCHAR NOT NULL,
    ACTION_NAME VARCHAR NOT NULL,
    OBJECT_NAME VARCHAR NOT NULL,
    ROW_COUNT NUMBER,
    OUTCOME VARCHAR NOT NULL,
    REFUSED BOOLEAN NOT NULL,
    REFUSAL_REASON VARCHAR,
    CITATION_COUNT NUMBER NOT NULL,
    CONSTRAINT PK_AGENT_INTERACTION_AUDIT PRIMARY KEY (AUDIT_ID)
);

CREATE TABLE IF NOT EXISTS PHARMARETAIL_AI_CONTROL_TOWER.AI_LOGS.AGENT_ACTION_DRAFT (
    DRAFT_ID VARCHAR NOT NULL,
    QUERY_HASH VARCHAR NOT NULL,
    CREATED_AT TIMESTAMP_NTZ NOT NULL,
    ACTOR VARCHAR NOT NULL,
    TITLE VARCHAR NOT NULL,
    BODY VARCHAR NOT NULL,
    TARGET_SYSTEM VARCHAR NOT NULL,
    PRIORITY VARCHAR NOT NULL,
    STATUS VARCHAR NOT NULL,
    REQUIRES_HUMAN_APPROVAL BOOLEAN NOT NULL,
    CITATION_COUNT NUMBER NOT NULL,
    CONSTRAINT PK_AGENT_ACTION_DRAFT PRIMARY KEY (DRAFT_ID),
    CONSTRAINT CK_AGENT_DRAFT_APPROVAL CHECK (REQUIRES_HUMAN_APPROVAL = TRUE),
    CONSTRAINT CK_AGENT_DRAFT_STATUS CHECK (STATUS = 'DRAFT_PENDING_APPROVAL')
);

-- The agent identity may only APPEND. It is never granted UPDATE or DELETE, so
-- the audit and draft tables remain immutable once written.
GRANT INSERT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.AI_LOGS.AGENT_INTERACTION_AUDIT
TO ROLE PHARMARETAIL_AI_APP;
GRANT INSERT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.AI_LOGS.AGENT_ACTION_DRAFT
TO ROLE PHARMARETAIL_AI_APP;

-- Supply-chain analysts and admins may read the trail for human review.
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.AI_LOGS.AGENT_INTERACTION_AUDIT
TO ROLE PHARMARETAIL_SUPPLY_CHAIN_ANALYST;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.AI_LOGS.AGENT_ACTION_DRAFT
TO ROLE PHARMARETAIL_SUPPLY_CHAIN_ANALYST;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.AI_LOGS.AGENT_INTERACTION_AUDIT
TO ROLE PHARMARETAIL_ADMIN;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.AI_LOGS.AGENT_ACTION_DRAFT
TO ROLE PHARMARETAIL_ADMIN;
