-- Post-dbt deployment: MARTS is managed access, so only its schema owner can
-- grant model access. Run as PHARMARETAIL_ADMIN after dbt has created tables.
USE ROLE PHARMARETAIL_ADMIN;
ALTER SESSION SET QUERY_TAG = 'PHARMARETAIL_PHASE4_MODEL_GRANTS';

-- Remove the Phase 1 broad AI_APP grant before adding only approved objects.
REVOKE SELECT ON ALL TABLES IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
FROM ROLE PHARMARETAIL_AI_APP;
REVOKE SELECT ON ALL VIEWS IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
FROM ROLE PHARMARETAIL_AI_APP;
REVOKE SELECT ON FUTURE TABLES IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
FROM ROLE PHARMARETAIL_AI_APP;
REVOKE SELECT ON FUTURE VIEWS IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
FROM ROLE PHARMARETAIL_AI_APP;

GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.DIM_DATE
TO ROLE PHARMARETAIL_AI_APP;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.DIM_STORE
TO ROLE PHARMARETAIL_AI_APP;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.DIM_PRODUCT
TO ROLE PHARMARETAIL_AI_APP;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.DIM_SUPPLIER
TO ROLE PHARMARETAIL_AI_APP;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.FCT_INVENTORY_SNAPSHOT
TO ROLE PHARMARETAIL_AI_APP;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.FCT_SUPPLIER_DELIVERY
TO ROLE PHARMARETAIL_AI_APP;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.FCT_STOCKOUT_EVENT
TO ROLE PHARMARETAIL_AI_APP;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.FCT_PROMOTION
TO ROLE PHARMARETAIL_AI_APP;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.FCT_INCIDENT
TO ROLE PHARMARETAIL_AI_APP;

GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.DIM_DATE
TO ROLE PHARMARETAIL_STORE_MANAGER;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.DIM_STORE
TO ROLE PHARMARETAIL_STORE_MANAGER;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.DIM_PRODUCT
TO ROLE PHARMARETAIL_STORE_MANAGER;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.DIM_SUPPLIER
TO ROLE PHARMARETAIL_STORE_MANAGER;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.FCT_INVENTORY_SNAPSHOT
TO ROLE PHARMARETAIL_STORE_MANAGER;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.FCT_SUPPLIER_DELIVERY
TO ROLE PHARMARETAIL_STORE_MANAGER;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.FCT_STOCKOUT_EVENT
TO ROLE PHARMARETAIL_STORE_MANAGER;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.FCT_PROMOTION
TO ROLE PHARMARETAIL_STORE_MANAGER;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.FCT_INCIDENT
TO ROLE PHARMARETAIL_STORE_MANAGER;

GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.DIM_DATE
TO ROLE PHARMARETAIL_AREA_MANAGER;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.DIM_STORE
TO ROLE PHARMARETAIL_AREA_MANAGER;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.DIM_PRODUCT
TO ROLE PHARMARETAIL_AREA_MANAGER;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.DIM_SUPPLIER
TO ROLE PHARMARETAIL_AREA_MANAGER;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.FCT_INVENTORY_SNAPSHOT
TO ROLE PHARMARETAIL_AREA_MANAGER;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.FCT_SUPPLIER_DELIVERY
TO ROLE PHARMARETAIL_AREA_MANAGER;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.FCT_STOCKOUT_EVENT
TO ROLE PHARMARETAIL_AREA_MANAGER;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.FCT_PROMOTION
TO ROLE PHARMARETAIL_AREA_MANAGER;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.FCT_INCIDENT
TO ROLE PHARMARETAIL_AREA_MANAGER;

-- Remove any legacy schema-wide grant and expose only the governed operational
-- surface required for national supply-chain investigations.
REVOKE SELECT ON ALL TABLES IN SCHEMA PHARMARETAIL_AI_CONTROL_TOWER.MARTS
FROM ROLE PHARMARETAIL_SUPPLY_CHAIN_ANALYST;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.DIM_DATE
TO ROLE PHARMARETAIL_SUPPLY_CHAIN_ANALYST;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.DIM_STORE
TO ROLE PHARMARETAIL_SUPPLY_CHAIN_ANALYST;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.DIM_PRODUCT
TO ROLE PHARMARETAIL_SUPPLY_CHAIN_ANALYST;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.DIM_SUPPLIER
TO ROLE PHARMARETAIL_SUPPLY_CHAIN_ANALYST;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.FCT_INVENTORY_SNAPSHOT
TO ROLE PHARMARETAIL_SUPPLY_CHAIN_ANALYST;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.FCT_SUPPLIER_DELIVERY
TO ROLE PHARMARETAIL_SUPPLY_CHAIN_ANALYST;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.FCT_STOCKOUT_EVENT
TO ROLE PHARMARETAIL_SUPPLY_CHAIN_ANALYST;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.FCT_PROMOTION
TO ROLE PHARMARETAIL_SUPPLY_CHAIN_ANALYST;
GRANT SELECT ON TABLE PHARMARETAIL_AI_CONTROL_TOWER.MARTS.FCT_INCIDENT
TO ROLE PHARMARETAIL_SUPPLY_CHAIN_ANALYST;
